name: Anyodesk
on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Print folder details
        shell: pwsh
        run: |
          Get-ChildItem | Format-Table FullName

      - name: Open anyodesk
        shell: pwsh
        run: |
          powershell -File .\bringup_anyodesk.ps1
