name: CI_Flash

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  take-screenshot:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Take Desktop Screenshot
        run: powershell -Command "Add-Type -AssemblyName System.Drawing; $bitmap = New-Object System.Drawing.Bitmap ([System.Windows.Forms.SystemInformation]::PrimaryMonitorSize.Width, [System.Windows.Forms.SystemInformation]::PrimaryMonitorSize.Height); $graphics = [System.Drawing.Graphics]::FromImage($bitmap); $graphics.CopyFromScreen(0, 0, 0, 0, $bitmap.Size); $bitmap.Save(""screenshot.png"", [System.Drawing.Imaging.ImageFormat]::Png); $graphics.Dispose(); $bitmap.Dispose()"
      - name: Upload Screenshot
        uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: screenshot.png
      # - uses: actions/checkout@v3
      # - name: Take Desktop Screenshot
      #   run: powershell -Command "Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.Clipboard]::SetImage([System.Windows.Forms.ScreenCapture]::CaptureDesktop())"
      # - name: Save Screenshot
      #   run: powershell -Command "Add-Type -AssemblyName System.Drawing; [System.Drawing.Bitmap]::FromClipboard().Save('screenshot.png')"
      # - name: Upload Screenshot
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: screenshot
      #     path: screenshot.png
      # - uses: actions/checkout@v3
      # - name: Take Desktop Screenshot
      #   uses: OrbitalOwen/desktop-screenshot-action@v0.1
      #   with:
      #     file-name: 'desktop.jpg'
