name: CI_Flash

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  take-screenshot:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Take Desktop Screenshot
        run: |
          Add-Type -AssemblyName System.Windows.Forms
          Add-Type -AssemblyName System.Drawing
          $bitmap = New-Object Drawing.Bitmap([System.Windows.Forms.Screen]::PrimaryScreen.Bounds.Width, [System.Windows.Forms.Screen]::PrimaryScreen.Bounds.Height)
          $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
          $graphics.CopyFromScreen([System.Windows.Forms.Screen]::PrimaryScreen.Bounds.Location, [System.Drawing.Point]::Empty, $butmap.Size)
          $bitmap.Save("$env:GITHUB_WORKSPACE\screenshot.png",[System.Drawing.Imaging.ImageFormat]::Png)
          
      - name: Upload Screenshot
        uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: ${{ github.workspace }}/screenshot.png
      # - uses: actions/checkout@v3
      # - name: Take Desktop Screenshot
      #   run: powershell -Command "Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.Clipboard]::SetImage([System.Windows.Forms.ScreenCapture]::CaptureDesktop())"
      # - name: Save Screenshot
      #   run: powershell -Command "Add-Type -AssemblyName System.Drawing; [System.Drawing.Bitmap]::FromClipboard().Save('screenshot.png')"
      # - name: Upload Screenshot
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: screenshot
      #     path: screenshot.png
      # - uses: actions/checkout@v3
      # - name: Take Desktop Screenshot
      #   uses: OrbitalOwen/desktop-screenshot-action@v0.1
      #   with:
      #     file-name: 'desktop.jpg'
