name: Test_Date

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  one:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script - $(date + '%d-%m-%Y_%H-%M-%S')
        run: echo Hello, world!
        
      - name: Run a script with input parameters
        id: example_step
        run: |
          echo "Input Parameter 1: ${{ env.param1 }}"
        env:
          param1: $(date + '%d-%m-%Y_%H-%M-%S')
  two:
    runs-on: windows-latest

    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script - $(date + '%d-%m-%Y_%H-%M-%S')
        run: echo Hello, world!
