name: Upgrade Google Chrome Test
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Install dependencies
      #   shell: bash
      #   run: |
      #     set -ex
      #     wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      #     sudo apt install ./google-chrome-stable_current_amd64.deb
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | sed 's/Google Chrome //; s/ .*//')
          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d $HOME
          rm chromedriver_linux64.zip
          sudo mv -f $HOME/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          
      - name: Print Google Chrome details
        shell: bash
        run: |
          google-chrome --version
          chromedriver --version
          
  
