name: Upgrade Google Chrome Test
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version  # Log Chrome version

      - name: Install ChromeDriver
        run: |
          # Remove any existing ChromeDriver to avoid conflicts
          sudo rm -f /usr/local/bin/chromedriver
          
          # Get the exact Chrome version
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          echo "Detected Chrome version: $CHROME_VERSION"

          # Download ChromeDriver from the new URL structure
          wget -N https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chromedriver-linux64.zip -O chromedriver.zip
          
          # Unzip and move to /usr/local/bin
          unzip -o chromedriver.zip -d $HOME
          $HOME/chromedriver-linux64 --version
          sudo mv -f $HOME/chromedriver-linux64 /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          rm chromedriver.zip
          
          # Verify the ChromeDriver version
          chromedriver --version
          
      - name: Print Google Chrome and ChromeDriver details
        run: |
          google-chrome --version
          chromedriver --version
