name: Upgrade Google Chrome Test2
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver_manager

      - name: Upgrade Google Chrome
        run: |
          sudo apt-get update
          sudo apt --only-upgrade install google-chrome-stable

      - name: Magic of web_driver_manager
        run: |
          python -c "from webdriver_manager.chrome import ChromeDriverManager; print(ChromeDriverManager().install())"

      # - name: Uninstall existing Google Chrome (if any)
      #   run: |
      #     sudo apt-get remove --purge google-chrome-stable
      #     sudo apt-get autoremove

      # - name: Install google chrome and driver
      #   id: setup-chrome
      #   uses: browser-actions/setup-chrome@v1
      #   with:
      #     chrome-version: 'stable'
      #     install-chromedriver: true
                  
      - name: Print Google Chrome and ChromeDriver details
        run: |
          google-chrome --version
          chromedriver --version
          # echo "Chrome installation path: ${{ steps.setup-chrome.outputs.chrome-path }}"
          # echo "ChromeDriver installation path: ${{ steps.setup-chrome.outputs.chromedriver-path }}"
          # echo "Chrome version: ${{ steps.setup-chrome.outputs.chrome-version }}"
          # echo "ChromeDriver version ${{ steps.setup-chrome.outputs.chromedriver-version }}"
